# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MaskedDataset": "00_data.ipynb",
         "MBPPDataset": "00_data.ipynb",
         "get_grouped_params": "01_models.ipynb",
         "Completeformer": "01_models.ipynb",
         "train": "04_cli.ipynb",
         "merge_completions": "03_eval.ipynb",
         "FunctionalEvaluator": "03_eval.ipynb",
         "first_block": "03_eval.ipynb",
         "complete_code": "03_eval.ipynb",
         "get_block_offsets": "03_eval.ipynb",
         "PY_LANGUAGE": "03_eval.ipynb",
         "parser": "03_eval.ipynb",
         "HumanEvalEvaluator": "03_eval.ipynb",
         "logger": "04_cli.ipynb",
         "URLs": "04_cli.ipynb",
         "download": "04_cli.ipynb",
         "evaluate": "04_cli.ipynb",
         "reproduce": "04_cli.ipynb",
         "completeformer": "04_cli.ipynb"}

modules = ["data.py",
           "models.py",
           "train.py",
           "eval.py",
           "cli.py"]

doc_url = "https://wm-semeru.github.io/completeformer/"

git_url = "https://github.com/wm-semeru/completeformer/tree/main/"

def custom_doc_links(name): return None
